[Sound Theme]
Name=Plasma Mobile
Name[ca]=Plasma Mobile
Name[es]=Plasma Mobile
Name[eu]=Plasma Mugikorra
Name[fr]=Plasma Mobile
Name[it]=Plasma Mobile
Name[ko]=Plasma 모바일
Name[nl]=Plasma-mobiel
Name[pt_BR]=Plasma Mobile
Name[sl]=Plasma Mobile
Name[sv]=Plasma mobil
Name[uk]=Мобільна Плазма
Name[x-test]=xxPlasma Mobilexx
Comment=Plasma Mobile sound theme
Comment[ca]=Tema de so del Plasma Mobile
Comment[es]=Tema de sonidos de Plasma Mobile
Comment[eu]=Plasma Mugikorreko soinu-gaia
Comment[fr]=Thème sonore de Plasma Mobile
Comment[it]=Tema sonoro di Plasma Mobile
Comment[ko]=Plasma 모바일 사운드 테마
Comment[nl]=Geluidsthema van Plasma-mobiel
Comment[pt_BR]=Tema de som do Plasma Mobile
Comment[sl]=Glasbena tema Plasma Mobile
Comment[sv]=Plasma Mobil ljudtema
Comment[uk]=Звукова тема Мобільної Плазми
Comment[x-test]=xxPlasma Mobile sound themexx
Directories=stereo

[stereo]
OutputProfile=stereo
